name: slurm-salloc
description: Allocate an interactive Slurm session with salloc and run a script
inputs:
  job-name:
    required: true
  partition:
    required: true
  account:
    required: false
    default: "co2su"
  time:
    required: false
    default: 00:30:00
  cpus:
    required: false
    default: "1"
  gpus:
    required: false
    default: "1"
  run-script:
    required: true
    description: Multi-line bash job executed inside the allocated session
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        # Create Slurm job script
        set -euo pipefail

        cat > job.sh <<'EOF'
        #!/bin/bash
        echo "Node: $(hostname)"
        echo "Start: $(date -Is)"
        EOF

        cat >> job.sh <<'EOF'
        ${{ inputs.run-script }}
        EOF

        cat >> job.sh <<'EOF'
        STATUS=$?
        echo "End: $(date -Is) (exit=$STATUS)"
        exit $STATUS
        EOF

        chmod +x job.sh

        echo "Requesting allocation with salloc..."
        cmd=(
          salloc
          -p ${{ inputs.partition }}
          -A ${{ inputs.account }}
          --gres=gpu:${{ inputs.gpus }}
          --time=${{ inputs.time }}
          --cpus-per-task=${{ inputs.cpus }}
          --job-name=${{ inputs.job-name }}
          srun --export=USER,HOME,TERM,RDHPC_PARTITION,PYWRAP,PROGRAMMING_MODEL job.sh
        )

        echo -n "Command: "
        printf '%q ' "${cmd[@]}"
        echo
        echo "For run script:"
        cat job.sh
        echo "ENVIRONMENT VARIABLES:"
        env | sort

        # Execute the command
        "${cmd[@]}"