/**
 * @file test_sep_params_binary.cc
 * @brief Unit tests for SepParams binary data reading
 *
 * These tests require test data files generated by generate_sep_test_data.py
 * Run: python generate_sep_test_data.py tests/units/data/sep/
 */

#include "sep_params.h"

#include <gtest/gtest.h>

#include <cmath>
#include <string>
#include <vector>

namespace model {
namespace {

// Type alias
using SepParamsFloat = SepParams<float, int>;

// Path to test data (generated by Python script)
const std::string kTestDataDir = "tests/units/data/sep/";

// Tolerance for floating point comparisons
constexpr float kFloatTol = 1e-5f;
constexpr double kDoubleTol = 1e-10;

// =============================================================================
// Test: Index-based data (value = ix + iy*1000 + iz*1000000)
// =============================================================================

class SepParamsBinaryIndexTest : public ::testing::Test {
 protected:
  void SetUp() override {
    params_ = std::make_unique<SepParamsFloat>(kTestDataDir + "test_index.H");
    data_ = params_->readBinaryData<float>();
  }

  std::unique_ptr<SepParamsFloat> params_;
  std::vector<float> data_;
};

TEST_F(SepParamsBinaryIndexTest, ReadsDimensions) {
  EXPECT_EQ(params_->getN1(), 10);
  EXPECT_EQ(params_->getN2(), 8);
  EXPECT_EQ(params_->getN3(), 5);
}

TEST_F(SepParamsBinaryIndexTest, ReadsCorrectSize) {
  EXPECT_EQ(data_.size(), 10 * 8 * 5);
}

TEST_F(SepParamsBinaryIndexTest, ReadsOrigin) {
  // Value at (0,0,0) should be 0
  float val = params_->getValue(data_, 0, 0, 0);
  EXPECT_FLOAT_EQ(val, 0.0f);
}

TEST_F(SepParamsBinaryIndexTest, ReadsXAxis) {
  // Value at (1,0,0) should be 1
  float val = params_->getValue(data_, 1, 0, 0);
  EXPECT_FLOAT_EQ(val, 1.0f);

  // Value at (5,0,0) should be 5
  val = params_->getValue(data_, 5, 0, 0);
  EXPECT_FLOAT_EQ(val, 5.0f);
}

TEST_F(SepParamsBinaryIndexTest, ReadsYAxis) {
  // Value at (0,1,0) should be 1000
  float val = params_->getValue(data_, 0, 1, 0);
  EXPECT_FLOAT_EQ(val, 1000.0f);

  // Value at (0,3,0) should be 3000
  val = params_->getValue(data_, 0, 3, 0);
  EXPECT_FLOAT_EQ(val, 3000.0f);
}

TEST_F(SepParamsBinaryIndexTest, ReadsZAxis) {
  // Value at (0,0,1) should be 1000000
  float val = params_->getValue(data_, 0, 0, 1);
  EXPECT_FLOAT_EQ(val, 1000000.0f);

  // Value at (0,0,2) should be 2000000
  val = params_->getValue(data_, 0, 0, 2);
  EXPECT_FLOAT_EQ(val, 2000000.0f);
}

TEST_F(SepParamsBinaryIndexTest, ReadsMixedIndices) {
  // Value at (5,3,2) should be 5 + 3*1000 + 2*1000000 = 2003005
  float val = params_->getValue(data_, 5, 3, 2);
  EXPECT_FLOAT_EQ(val, 2003005.0f);

  // Value at (9,7,4) should be 9 + 7*1000 + 4*1000000 = 4007009
  val = params_->getValue(data_, 9, 7, 4);
  EXPECT_FLOAT_EQ(val, 4007009.0f);
}

TEST_F(SepParamsBinaryIndexTest, DirectIndexAccess) {
  // Verify direct array access matches getValue
  // SEP order: data[ix + iy * n1 + iz * n1 * n2]
  int n1 = params_->getN1();
  int n2 = params_->getN2();

  int ix = 3, iy = 2, iz = 1;
  size_t idx = ix + iy * n1 + iz * n1 * n2;

  float expected = ix + iy * 1000.0f + iz * 1000000.0f;
  EXPECT_FLOAT_EQ(data_[idx], expected);
}

// =============================================================================
// Test: Coordinate-based data (value = x + y + z physical coordinates)
// =============================================================================

class SepParamsBinaryCoordTest : public ::testing::Test {
 protected:
  void SetUp() override {
    params_ = std::make_unique<SepParamsFloat>(kTestDataDir + "test_coords.H");
    data_ = params_->readBinaryData<float>();
  }

  std::unique_ptr<SepParamsFloat> params_;
  std::vector<float> data_;
};

TEST_F(SepParamsBinaryCoordTest, ReadsDimensions) {
  EXPECT_EQ(params_->getN1(), 20);
  EXPECT_EQ(params_->getN2(), 15);
  EXPECT_EQ(params_->getN3(), 10);
}

TEST_F(SepParamsBinaryCoordTest, ReadsSpacing) {
  EXPECT_FLOAT_EQ(params_->getD1(), 10.0f);
  EXPECT_FLOAT_EQ(params_->getD2(), 10.0f);
  EXPECT_FLOAT_EQ(params_->getD3(), 5.0f);
}

TEST_F(SepParamsBinaryCoordTest, ReadsOriginValue) {
  // At (0,0,0), coord = (0,0,0), sum = 0
  float val = params_->getValue(data_, 0, 0, 0);
  EXPECT_FLOAT_EQ(val, 0.0f);
}

TEST_F(SepParamsBinaryCoordTest, ReadsXCoordinate) {
  // At (1,0,0), coord = (10,0,0), sum = 10
  float val = params_->getValue(data_, 1, 0, 0);
  EXPECT_FLOAT_EQ(val, 10.0f);
}

TEST_F(SepParamsBinaryCoordTest, ReadsYCoordinate) {
  // At (0,1,0), coord = (0,10,0), sum = 10
  float val = params_->getValue(data_, 0, 1, 0);
  EXPECT_FLOAT_EQ(val, 10.0f);
}

TEST_F(SepParamsBinaryCoordTest, ReadsZCoordinate) {
  // At (0,0,1), coord = (0,0,5), sum = 5
  float val = params_->getValue(data_, 0, 0, 1);
  EXPECT_FLOAT_EQ(val, 5.0f);
}

TEST_F(SepParamsBinaryCoordTest, ReadsMixedCoordinates) {
  // At (10,7,5), coord = (100,70,25), sum = 195
  float val = params_->getValue(data_, 10, 7, 5);
  EXPECT_FLOAT_EQ(val, 195.0f);
}

// =============================================================================
// Test: Constant velocity model
// =============================================================================

TEST(SepParamsBinaryConstant, ReadsConstantValue) {
  SepParamsFloat params(kTestDataDir + "test_constant_vp.H");
  std::vector<float> data = params.readBinaryData<float>();

  EXPECT_EQ(data.size(), 50 * 50 * 25);

  // All values should be 2500
  for (size_t i = 0; i < data.size(); ++i) {
    EXPECT_FLOAT_EQ(data[i], 2500.0f) << "Mismatch at index " << i;
  }
}

// =============================================================================
// Test: Layered velocity model
// =============================================================================

TEST(SepParamsBinaryLayered, ReadsLayerValues) {
  SepParamsFloat params(kTestDataDir + "test_layered_vp.H");
  std::vector<float> data = params.readBinaryData<float>();

  int n1 = params.getN1();
  int n2 = params.getN2();
  int n3 = params.getN3();

  // Layer boundaries at z fractions: 0.0, 0.2, 0.5, 0.8
  // n3 = 50, so:
  //   z=0-9   (0.0-0.2): 1500
  //   z=10-24 (0.2-0.5): 2000
  //   z=25-39 (0.5-0.8): 2500
  //   z=40-49 (0.8-1.0): 3000

  // Check layer 1 (z=5)
  float val = params.getValue(data, 0, 0, 5);
  EXPECT_FLOAT_EQ(val, 1500.0f);

  // Check layer 2 (z=15)
  val = params.getValue(data, 0, 0, 15);
  EXPECT_FLOAT_EQ(val, 2000.0f);

  // Check layer 3 (z=30)
  val = params.getValue(data, 0, 0, 30);
  EXPECT_FLOAT_EQ(val, 2500.0f);

  // Check layer 4 (z=45)
  val = params.getValue(data, 0, 0, 45);
  EXPECT_FLOAT_EQ(val, 3000.0f);

  // Verify layers are constant in x and y
  for (int iy = 0; iy < n2; ++iy) {
    for (int ix = 0; ix < n1; ++ix) {
      EXPECT_FLOAT_EQ(params.getValue(data, ix, iy, 5), 1500.0f);
    }
  }
}

// =============================================================================
// Test: Double precision data
// =============================================================================

TEST(SepParamsBinaryDouble, ReadsDoublePrecision) {
  SepParams<double, int> params(kTestDataDir + "test_double.H");

  EXPECT_EQ(params.getEsize(), 8);
  EXPECT_EQ(params.getN1(), 10);
  EXPECT_EQ(params.getN2(), 10);
  EXPECT_EQ(params.getN3(), 10);

  std::vector<double> data = params.readBinaryData<double>();
  EXPECT_EQ(data.size(), 10 * 10 * 10);

  // Value at (5,3,2) = 5 + 3*1000 + 2*1000000 = 2003005
  double val = params.getValue(data, 5, 3, 2);
  EXPECT_DOUBLE_EQ(val, 2003005.0);
}

// =============================================================================
// Test: XDR (big-endian) format
// =============================================================================

TEST(SepParamsBinaryXdr, ReadsXdrFormat) {
  SepParamsFloat params(kTestDataDir + "test_xdr.H");
  std::vector<float> data = params.readBinaryData<float>();

  EXPECT_EQ(params.getN1(), 10);
  EXPECT_EQ(params.getN2(), 8);
  EXPECT_EQ(params.getN3(), 5);
  EXPECT_EQ(data.size(), 10 * 8 * 5);

  // Same index-based values as test_index
  EXPECT_FLOAT_EQ(params.getValue(data, 0, 0, 0), 0.0f);
  EXPECT_FLOAT_EQ(params.getValue(data, 1, 0, 0), 1.0f);
  EXPECT_FLOAT_EQ(params.getValue(data, 0, 1, 0), 1000.0f);
  EXPECT_FLOAT_EQ(params.getValue(data, 0, 0, 1), 1000000.0f);
  EXPECT_FLOAT_EQ(params.getValue(data, 5, 3, 2), 2003005.0f);
}

// =============================================================================
// Test: Single value (1x1x1 edge case)
// =============================================================================

TEST(SepParamsBinarySingle, ReadsSingleValue) {
  SepParamsFloat params(kTestDataDir + "test_single.H");
  std::vector<float> data = params.readBinaryData<float>();

  EXPECT_EQ(params.getN1(), 1);
  EXPECT_EQ(params.getN2(), 1);
  EXPECT_EQ(params.getN3(), 1);
  EXPECT_EQ(data.size(), 1);
  EXPECT_FLOAT_EQ(data[0], 42.0f);
}

// =============================================================================
// Test: Non-zero origin
// =============================================================================

TEST(SepParamsBinaryOrigin, ReadsNonZeroOrigin) {
  SepParamsFloat params(kTestDataDir + "test_origin.H");

  EXPECT_FLOAT_EQ(params.getO1(), 100.0f);
  EXPECT_FLOAT_EQ(params.getO2(), 200.0f);
  EXPECT_FLOAT_EQ(params.getO3(), -50.0f);

  std::vector<float> data = params.readBinaryData<float>();

  // Value at (0,0,0) = o1 + o2 + o3 = 100 + 200 + (-50) = 250
  float val = params.getValue(data, 0, 0, 0);
  EXPECT_FLOAT_EQ(val, 250.0f);

  // Value at (1,0,0) = (100+5) + 200 + (-50) = 255
  val = params.getValue(data, 1, 0, 0);
  EXPECT_FLOAT_EQ(val, 255.0f);
}

// =============================================================================
// Test: Slice reading
// =============================================================================

TEST(SepParamsBinarySlice, ReadsSliceXY) {
  SepParamsFloat params(kTestDataDir + "test_index.H");

  int n1 = params.getN1();
  int n2 = params.getN2();

  // Read slice at z=2
  std::vector<float> slice = params.readSliceXY<float>(2);

  EXPECT_EQ(slice.size(), n1 * n2);

  // All values in this slice should have iz=2, so base = 2*1000000
  for (int iy = 0; iy < n2; ++iy) {
    for (int ix = 0; ix < n1; ++ix) {
      float expected = ix + iy * 1000.0f + 2.0f * 1000000.0f;
      size_t idx = ix + iy * n1;
      EXPECT_FLOAT_EQ(slice[idx], expected)
          << "Mismatch at (" << ix << "," << iy << ")";
    }
  }
}

TEST(SepParamsBinarySlice, SliceOutOfRangeThrows) {
  SepParamsFloat params(kTestDataDir + "test_index.H");

  // n3 = 5, so valid indices are 0-4
  EXPECT_THROW(params.readSliceXY<float>(5), std::runtime_error);
  EXPECT_THROW(params.readSliceXY<float>(-1), std::runtime_error);
}

// =============================================================================
// Test: Type conversion
// =============================================================================

TEST(SepParamsBinaryConvert, FloatToDouble) {
  SepParamsFloat params(kTestDataDir + "test_index.H");

  // Read float data as double
  std::vector<double> data = params.readBinaryData<double>();

  EXPECT_EQ(data.size(), 10 * 8 * 5);

  // Values should be converted correctly
  double val = params.getValue(data, 5, 3, 2);
  EXPECT_DOUBLE_EQ(val, 2003005.0);
}

// =============================================================================
// Test: Error handling
// =============================================================================

TEST(SepParamsBinaryError, MissingDataFileThrows) {
  // Create a header pointing to non-existent binary file
  // This would require creating a temp file, skip for now
}

}  // namespace
}  // namespace model
