#!/usr/bin/env python3
"""
Generate SEP format test data files for testing SepParams binary reader.

This script creates:
1. SEP header files (.H)
2. Binary data files (.bin) with known values

The data is stored in Fortran order (column-major):
  - n1 (x) is the fastest varying axis
  - n2 (y) is the middle axis
  - n3 (z) is the slowest varying axis

Usage:
    python generate_sep_test_data.py [output_directory]
"""

import numpy as np
import struct
import os
import sys


def write_sep_header(filename, n1, n2, n3, d1, d2, d3, o1, o2, o3,
                     data_file, esize=4, data_format="native_float",
                     data_label="Test data", order=3):
    """Write a SEP header file."""
    with open(filename, 'w') as f:
        f.write(f"# SEP test data generated by generate_sep_test_data.py\n")
        f.write(f"n1={n1}\n")
        f.write(f"n2={n2}\n")
        f.write(f"n3={n3}\n")
        f.write(f"d1={d1}\n")
        f.write(f"d2={d2}\n")
        f.write(f"d3={d3}\n")
        f.write(f"o1={o1}\n")
        f.write(f"o2={o2}\n")
        f.write(f"o3={o3}\n")
        f.write(f"esize={esize}\n")
        f.write(f"data_format={data_format}\n")
        f.write(f"data_label={data_label}\n")
        f.write(f"in={data_file}\n")
        f.write(f"order={order}\n")
        f.write(f"model_on_node=true\n")
        f.write(f"elastic=false\n")
    print(f"  Created header: {filename}")


def write_binary_native_float(filename, data):
    """Write binary data in native float format."""
    with open(filename, 'wb') as f:
        # Flatten in Fortran order (column-major) and write
        data.astype(np.float32).flatten(order='F').tofile(f)
    print(f"  Created binary: {filename} ({os.path.getsize(filename)} bytes)")


def write_binary_native_double(filename, data):
    """Write binary data in native double format."""
    with open(filename, 'wb') as f:
        data.astype(np.float64).flatten(order='F').tofile(f)
    print(f"  Created binary: {filename} ({os.path.getsize(filename)} bytes)")


def write_binary_xdr_float(filename, data):
    """Write binary data in XDR (big-endian) float format."""
    with open(filename, 'wb') as f:
        # Flatten in Fortran order and write as big-endian
        flat_data = data.astype(np.float32).flatten(order='F')
        f.write(flat_data.astype('>f4').tobytes())
    print(f"  Created binary (XDR): {filename} ({os.path.getsize(filename)} bytes)")


def generate_index_data(n1, n2, n3):
    """
    Generate data where value = ix + iy * 1000 + iz * 1000000
    This makes it easy to verify correct reading order.
    """
    data = np.zeros((n1, n2, n3), dtype=np.float32)
    for iz in range(n3):
        for iy in range(n2):
            for ix in range(n1):
                data[ix, iy, iz] = ix + iy * 1000 + iz * 1000000
    return data


def generate_coordinate_data(n1, n2, n3, d1, d2, d3, o1, o2, o3):
    """
    Generate data where value = physical coordinate sum (x + y + z)
    """
    data = np.zeros((n1, n2, n3), dtype=np.float32)
    for iz in range(n3):
        for iy in range(n2):
            for ix in range(n1):
                x = o1 + ix * d1
                y = o2 + iy * d2
                z = o3 + iz * d3
                data[ix, iy, iz] = x + y + z
    return data


def generate_gradient_data(n1, n2, n3):
    """
    Generate a simple linear gradient along each axis.
    value = ix / n1 + iy / n2 + iz / n3
    """
    data = np.zeros((n1, n2, n3), dtype=np.float32)
    for iz in range(n3):
        for iy in range(n2):
            for ix in range(n1):
                data[ix, iy, iz] = ix / n1 + iy / n2 + iz / n3
    return data


def generate_constant_data(n1, n2, n3, value):
    """Generate constant velocity/density model."""
    return np.full((n1, n2, n3), value, dtype=np.float32)


def generate_layered_data(n1, n2, n3, values):
    """
    Generate layered model (layers along z axis).
    values: list of (z_fraction, value) tuples
    """
    data = np.zeros((n1, n2, n3), dtype=np.float32)
    sorted_values = sorted(values, key=lambda x: x[0])

    for iz in range(n3):
        z_frac = iz / n3
        # Find appropriate layer
        layer_value = sorted_values[0][1]
        for z_thresh, val in sorted_values:
            if z_frac >= z_thresh:
                layer_value = val
        data[:, :, iz] = layer_value

    return data


def main(output_dir="."):
    """Generate all test data files."""
    os.makedirs(output_dir, exist_ok=True)

    print(f"Generating SEP test data in: {output_dir}\n")

    # =========================================================================
    # Test 1: Small cube with index-based values (easy to verify)
    # =========================================================================
    print("Test 1: Index-based values (10x8x5)")
    n1, n2, n3 = 10, 8, 5
    d1, d2, d3 = 1.0, 1.0, 1.0
    o1, o2, o3 = 0.0, 0.0, 0.0

    data = generate_index_data(n1, n2, n3)

    write_sep_header(
        os.path.join(output_dir, "test_index.H"),
        n1, n2, n3, d1, d2, d3, o1, o2, o3,
        "test_index.bin",
        data_label="Index test ix+iy*1000+iz*1000000"
    )
    write_binary_native_float(
        os.path.join(output_dir, "test_index.bin"),
        data
    )

    # Print some expected values for verification
    print(f"    Expected values:")
    print(f"      (0,0,0) = {data[0,0,0]}")
    print(f"      (1,0,0) = {data[1,0,0]}")
    print(f"      (0,1,0) = {data[0,1,0]}")
    print(f"      (0,0,1) = {data[0,0,1]}")
    print(f"      (5,3,2) = {data[5,3,2]}")
    print(f"      (9,7,4) = {data[9,7,4]}")
    print()

    # =========================================================================
    # Test 2: Coordinate-based values
    # =========================================================================
    print("Test 2: Coordinate-based values (20x15x10)")
    n1, n2, n3 = 20, 15, 10
    d1, d2, d3 = 10.0, 10.0, 5.0
    o1, o2, o3 = 0.0, 0.0, 0.0

    data = generate_coordinate_data(n1, n2, n3, d1, d2, d3, o1, o2, o3)

    write_sep_header(
        os.path.join(output_dir, "test_coords.H"),
        n1, n2, n3, d1, d2, d3, o1, o2, o3,
        "test_coords.bin",
        data_label="Coordinate sum x+y+z"
    )
    write_binary_native_float(
        os.path.join(output_dir, "test_coords.bin"),
        data
    )

    print(f"    Expected values:")
    print(f"      (0,0,0) -> coord (0,0,0) = {data[0,0,0]}")
    print(f"      (1,0,0) -> coord (10,0,0) = {data[1,0,0]}")
    print(f"      (0,1,0) -> coord (0,10,0) = {data[0,1,0]}")
    print(f"      (0,0,1) -> coord (0,0,5) = {data[0,0,1]}")
    print(f"      (10,7,5) -> coord (100,70,25) = {data[10,7,5]}")
    print()

    # =========================================================================
    # Test 3: Constant velocity model
    # =========================================================================
    print("Test 3: Constant velocity model (50x50x25)")
    n1, n2, n3 = 50, 50, 25
    d1, d2, d3 = 10.0, 10.0, 10.0
    o1, o2, o3 = 0.0, 0.0, 0.0
    velocity = 2500.0

    data = generate_constant_data(n1, n2, n3, velocity)

    write_sep_header(
        os.path.join(output_dir, "test_constant_vp.H"),
        n1, n2, n3, d1, d2, d3, o1, o2, o3,
        "test_constant_vp.bin",
        data_label="Velocity (m/s)"
    )
    write_binary_native_float(
        os.path.join(output_dir, "test_constant_vp.bin"),
        data
    )

    print(f"    All values = {velocity}")
    print()

    # =========================================================================
    # Test 4: Layered velocity model
    # =========================================================================
    print("Test 4: Layered velocity model (100x100x50)")
    n1, n2, n3 = 100, 100, 50
    d1, d2, d3 = 10.0, 10.0, 10.0
    o1, o2, o3 = 0.0, 0.0, 0.0

    # Define layers: (z_fraction, velocity)
    layers = [
        (0.0, 1500.0),   # Water layer
        (0.2, 2000.0),   # Sediment
        (0.5, 2500.0),   # Rock
        (0.8, 3000.0),   # Deep rock
    ]

    data = generate_layered_data(n1, n2, n3, layers)

    write_sep_header(
        os.path.join(output_dir, "test_layered_vp.H"),
        n1, n2, n3, d1, d2, d3, o1, o2, o3,
        "test_layered_vp.bin",
        data_label="Velocity (m/s)"
    )
    write_binary_native_float(
        os.path.join(output_dir, "test_layered_vp.bin"),
        data
    )

    print(f"    Layers: {layers}")
    print(f"    Value at z=0: {data[0,0,0]}")
    print(f"    Value at z=15: {data[0,0,15]}")
    print(f"    Value at z=30: {data[0,0,30]}")
    print(f"    Value at z=45: {data[0,0,45]}")
    print()

    # =========================================================================
    # Test 5: Double precision data
    # =========================================================================
    print("Test 5: Double precision (10x10x10)")
    n1, n2, n3 = 10, 10, 10
    d1, d2, d3 = 1.0, 1.0, 1.0
    o1, o2, o3 = 0.0, 0.0, 0.0

    data = generate_index_data(n1, n2, n3).astype(np.float64)

    write_sep_header(
        os.path.join(output_dir, "test_double.H"),
        n1, n2, n3, d1, d2, d3, o1, o2, o3,
        "test_double.bin",
        esize=8,
        data_format="native_double",
        data_label="Double precision test"
    )
    write_binary_native_double(
        os.path.join(output_dir, "test_double.bin"),
        data
    )
    print()

    # =========================================================================
    # Test 6: XDR (big-endian) format
    # =========================================================================
    print("Test 6: XDR format (big-endian) (10x8x5)")
    n1, n2, n3 = 10, 8, 5
    d1, d2, d3 = 1.0, 1.0, 1.0
    o1, o2, o3 = 0.0, 0.0, 0.0

    data = generate_index_data(n1, n2, n3)

    write_sep_header(
        os.path.join(output_dir, "test_xdr.H"),
        n1, n2, n3, d1, d2, d3, o1, o2, o3,
        "test_xdr.bin",
        data_format="xdr_float",
        data_label="XDR format test"
    )
    write_binary_xdr_float(
        os.path.join(output_dir, "test_xdr.bin"),
        data
    )
    print()

    # =========================================================================
    # Test 7: Single value (1x1x1) - edge case
    # =========================================================================
    print("Test 7: Single value (1x1x1)")
    data = np.array([[[42.0]]], dtype=np.float32)

    write_sep_header(
        os.path.join(output_dir, "test_single.H"),
        1, 1, 1, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0,
        "test_single.bin",
        data_label="Single value"
    )
    write_binary_native_float(
        os.path.join(output_dir, "test_single.bin"),
        data
    )
    print(f"    Value = 42.0")
    print()

    # =========================================================================
    # Test 8: Non-zero origin
    # =========================================================================
    print("Test 8: Non-zero origin (10x10x10)")
    n1, n2, n3 = 10, 10, 10
    d1, d2, d3 = 5.0, 5.0, 5.0
    o1, o2, o3 = 100.0, 200.0, -50.0

    data = generate_coordinate_data(n1, n2, n3, d1, d2, d3, o1, o2, o3)

    write_sep_header(
        os.path.join(output_dir, "test_origin.H"),
        n1, n2, n3, d1, d2, d3, o1, o2, o3,
        "test_origin.bin",
        data_label="Non-zero origin test"
    )
    write_binary_native_float(
        os.path.join(output_dir, "test_origin.bin"),
        data
    )
    print(f"    Origin: ({o1}, {o2}, {o3})")
    print(f"    Value at (0,0,0) = {o1}+{o2}+{o3} = {data[0,0,0]}")
    print()

    # =========================================================================
    # Summary
    # =========================================================================
    print("=" * 60)
    print("Generated files:")
    for f in sorted(os.listdir(output_dir)):
        filepath = os.path.join(output_dir, f)
        print(f"  {f:30s} {os.path.getsize(filepath):>10d} bytes")
    print("=" * 60)

    # Write a verification script
    verify_script = os.path.join(output_dir, "verify_data.py")
    with open(verify_script, 'w') as f:
        f.write('''#!/usr/bin/env python3
"""Quick verification of generated test data."""
import numpy as np

def read_sep_binary(header_file):
    """Read SEP header and binary data."""
    params = {}
    with open(header_file) as f:
        for line in f:
            if '=' in line and not line.startswith('#'):
                key, val = line.strip().split('=', 1)
                params[key.strip()] = val.strip()

    n1, n2, n3 = int(params['n1']), int(params['n2']), int(params['n3'])
    esize = int(params.get('esize', 4))
    data_format = params.get('data_format', 'native_float')

    import os
    bin_file = params['in']
    if not os.path.isabs(bin_file):
        bin_file = os.path.join(os.path.dirname(header_file), bin_file)

    dtype = np.float32 if esize == 4 else np.float64
    if 'xdr' in data_format:
        dtype = '>f4' if esize == 4 else '>f8'

    data = np.fromfile(bin_file, dtype=dtype)
    return data.reshape((n1, n2, n3), order='F')

# Test index data
print("Verifying test_index.H...")
data = read_sep_binary("test_index.H")
assert data[0,0,0] == 0, f"Expected 0, got {data[0,0,0]}"
assert data[1,0,0] == 1, f"Expected 1, got {data[1,0,0]}"
assert data[0,1,0] == 1000, f"Expected 1000, got {data[0,1,0]}"
assert data[0,0,1] == 1000000, f"Expected 1000000, got {data[0,0,1]}"
assert data[5,3,2] == 5 + 3*1000 + 2*1000000, f"Mismatch at (5,3,2)"
print("  PASSED")

print("\\nAll verifications passed!")
''')
    print(f"\nVerification script: {verify_script}")
    print("Run with: python verify_data.py")


if __name__ == "__main__":
    output_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    main(output_dir)
