#!/usr/bin/env sh

# ==============================================================================
# Script Name : tovideo.sh
# Description : This script take files snap??????.png generated by test_semsolver.py
#               and convert it into a MP4 video named output.mp4
# Author      : Alexis BANDET
# Date        : 2025-07-03
# Version     : 1.0
# ==============================================================================

ls snap*.png | sort >frames.txt
awk '{print "file \x27" $0 "\x27"}' frames.txt >input.txt
ffmpeg -r 30 -f concat -safe 0 -i input.txt -c:v libx264 -pix_fmt yuv420p output.mp4
