# ============================================================================
# DIFFERENTIATOR CONFIGURATION
# ============================================================================

# Define Implementation Limitations (Hard Bounds)
set(IMPL_LIMIT_DIFFERENTIATOR_ACOUSTIC_ORDER 3)
set(IMPL_LIMIT_DIFFERENTIATOR_ELASTIC_ORDER 3)

# Set Safe Defaults
set(TARGET_DIFFERENTIATOR_ACOUSTIC_ORDER ${IMPL_LIMIT_DIFFERENTIATOR_ACOUSTIC_ORDER})
set(TARGET_DIFFERENTIATOR_ELASTIC_ORDER ${IMPL_LIMIT_DIFFERENTIATOR_ELASTIC_ORDER})

# Determine User Requested Orders (via CLI overrides like -DMAX_DIFFERENTIATOR_ORDER=2)
# Acoustic Overrides
if(DEFINED MAX_DIFFERENTIATOR_ACOUSTIC_ORDER)
    set(TARGET_DIFFERENTIATOR_ACOUSTIC_ORDER ${MAX_DIFFERENTIATOR_ACOUSTIC_ORDER})
elseif(DEFINED MAX_DIFFERENTIATOR_ORDER)
    set(TARGET_DIFFERENTIATOR_ACOUSTIC_ORDER ${MAX_DIFFERENTIATOR_ORDER})
endif()

# Elastic Overrides
if(DEFINED MAX_DIFFERENTIATOR_ELASTIC_ORDER)
    set(TARGET_DIFFERENTIATOR_ELASTIC_ORDER ${MAX_DIFFERENTIATOR_ELASTIC_ORDER})
elseif(DEFINED MAX_DIFFERENTIATOR_ORDER)
    set(TARGET_DIFFERENTIATOR_ELASTIC_ORDER ${MAX_DIFFERENTIATOR_ORDER})
endif()

# Enforce Upper Bounds
if(TARGET_DIFFERENTIATOR_ACOUSTIC_ORDER GREATER IMPL_LIMIT_DIFFERENTIATOR_ACOUSTIC_ORDER)
    message(WARNING "Requested Differentiator Acoustic order (${TARGET_DIFFERENTIATOR_ACOUSTIC_ORDER}) exceeds limit. Clamping to ${IMPL_LIMIT_DIFFERENTIATOR_ACOUSTIC_ORDER}.")
    set(TARGET_DIFFERENTIATOR_ACOUSTIC_ORDER ${IMPL_LIMIT_DIFFERENTIATOR_ACOUSTIC_ORDER})
endif()

if(TARGET_DIFFERENTIATOR_ELASTIC_ORDER GREATER IMPL_LIMIT_DIFFERENTIATOR_ELASTIC_ORDER)
    message(WARNING "Requested Differentiator Elastic order (${TARGET_DIFFERENTIATOR_ELASTIC_ORDER}) exceeds limit. Clamping to ${IMPL_LIMIT_DIFFERENTIATOR_ELASTIC_ORDER}.")
    set(TARGET_DIFFERENTIATOR_ELASTIC_ORDER ${IMPL_LIMIT_DIFFERENTIATOR_ELASTIC_ORDER})
endif()


# ============================================================================
# SOLVER CONFIGURATION
# ============================================================================

# Define Implementation Limitations (Hard Bounds)
set(IMPL_LIMIT_SOLVER_ACOUSTIC_ORDER 9)
set(IMPL_LIMIT_SOLVER_ELASTIC_ORDER 9)
set(IMPL_LIMIT_SOLVER_ELASTOACOUSTIC_ORDER 9)

# Set Safe Defaults
set(TARGET_SOLVER_ACOUSTIC_ORDER ${IMPL_LIMIT_SOLVER_ACOUSTIC_ORDER})
set(TARGET_SOLVER_ELASTIC_ORDER ${IMPL_LIMIT_SOLVER_ELASTIC_ORDER})
set(TARGET_SOLVER_ELASTOACOUSTIC_ORDER ${IMPL_LIMIT_SOLVER_ELASTOACOUSTIC_ORDER})

# Determine User Requested Orders
# Acoustic Overrides
if(DEFINED MAX_SOLVER_ACOUSTIC_ORDER)
    set(TARGET_SOLVER_ACOUSTIC_ORDER ${MAX_SOLVER_ACOUSTIC_ORDER})
elseif(DEFINED MAX_SOLVER_ORDER)
    set(TARGET_SOLVER_ACOUSTIC_ORDER ${MAX_SOLVER_ORDER})
endif()

# Elastic Overrides
if(DEFINED MAX_SOLVER_ELASTIC_ORDER)
    set(TARGET_SOLVER_ELASTIC_ORDER ${MAX_SOLVER_ELASTIC_ORDER})
elseif(DEFINED MAX_SOLVER_ORDER)
    set(TARGET_SOLVER_ELASTIC_ORDER ${MAX_SOLVER_ORDER})
endif()

# Elastoacoustic Overrides
if(DEFINED MAX_SOLVER_ELASTOACOUSTIC_ORDER)
    set(TARGET_SOLVER_ELASTOACOUSTIC_ORDER ${MAX_SOLVER_ELASTOACOUSTIC_ORDER})
elseif(DEFINED MAX_SOLVER_ORDER)
    set(TARGET_SOLVER_ELASTOACOUSTIC_ORDER ${MAX_SOLVER_ORDER})
endif()

# Enforce Upper Bounds
if(TARGET_SOLVER_ACOUSTIC_ORDER GREATER IMPL_LIMIT_SOLVER_ACOUSTIC_ORDER)
    message(WARNING "Requested Solver Acoustic order (${TARGET_SOLVER_ACOUSTIC_ORDER}) exceeds limit. Clamping to ${IMPL_LIMIT_SOLVER_ACOUSTIC_ORDER}.")
    set(TARGET_SOLVER_ACOUSTIC_ORDER ${IMPL_LIMIT_SOLVER_ACOUSTIC_ORDER})
endif()

if(TARGET_SOLVER_ELASTIC_ORDER GREATER IMPL_LIMIT_SOLVER_ELASTIC_ORDER)
    message(WARNING "Requested Solver Elastic order (${TARGET_SOLVER_ELASTIC_ORDER}) exceeds limit. Clamping to ${IMPL_LIMIT_SOLVER_ELASTIC_ORDER}.")
    set(TARGET_SOLVER_ELASTIC_ORDER ${IMPL_LIMIT_SOLVER_ELASTIC_ORDER})
endif()

if(TARGET_SOLVER_ELASTOACOUSTIC_ORDER GREATER IMPL_LIMIT_SOLVER_ELASTOACOUSTIC_ORDER)
    message(WARNING "Requested Solver Elastoacoustic order (${TARGET_SOLVER_ELASTOACOUSTIC_ORDER}) exceeds limit. Clamping to ${IMPL_LIMIT_SOLVER_ELASTOACOUSTIC_ORDER}.")
    set(TARGET_SOLVER_ELASTOACOUSTIC_ORDER ${IMPL_LIMIT_SOLVER_ELASTOACOUSTIC_ORDER})
endif()
