name: Clear cache

#on:
#  workflow_dispatch:

on:
  pull_request:
    branches:
      - main

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear all caches
        uses: actions/github-script@v8
        with:
          script: |
            console.log("About to clear all caches")
            let page = 1
            let deleted = 0
            while (true) {
              const caches = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
                page: page,
              })
              console.log(`Fetched page ${page}, got ${caches.data.actions_caches.length} caches`)
              if (!caches.data.actions_caches.length) break
              for (const cache of caches.data.actions_caches) {
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                deleted++
              }
              page++
            }
            console.log(`Clear completed. Deleted ${deleted} caches.`)